name: Build and Deploy

on:
  push:
    branches:
      - main   # 你的源码分支
  workflow_dispatch: # 支持手动触发

permissions:
  contents: write  # 允许 Actions 推送到 gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout source
        uses: actions/checkout@v3

      # 2️⃣ 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: npm install

      # 4️⃣ 打包项目，生成 dist
      - name: Build project
        run: npm run build

      # 5️⃣ 部署 dist 到 gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true   # 强制覆盖 gh-pages 分支，避免冲突